- name: Set up the infrastructure on Docker daemon as debian containers
  hosts: control_node
  connection: local
  become: true
  tasks:
    - name: Ensure docker_net network exists within Docker
      community.docker.docker_network:
        name: docker_net
    - name: Ensure python-requests is installed for image fetching
      ansible.builtin.package:
        name: "python3-requests"
        state: present
    - name: Set up filehost container for nginx
      become: true
      community.docker.docker_container:
        name: nginx-filehost
        cap_drop: ALL
        detach: true
        hostname: nginx-filehost
        image: "python:3.14.0a5-slim-bookworm" #python-preinstalled bookworm
        pull: true
        restart_policy: "unless-stopped"
        state: started
        privileged: true
        interactive: true
        networks:
        - name: docker_net
    - name: Set up proxy container for nginx
      community.docker.docker_container:
        name: nginx-proxy
        cap_drop: ALL
        detach: true
        hostname: nginx-proxy
        image: "python:3.14.0a5-slim-bookworm" #python-preinstalled bookworm
        published_ports:
         - "80:80"
        pull: true
        restart_policy: "unless-stopped"
        state: started
        privileged: true
        interactive: true
        networks:
        - name: docker_net
    - name: Set up proxy container for Prometheus
      community.docker.docker_container:
        name: prometheus
        cap_drop: ALL
        detach: true
        hostname: prometheus
        image: "python:3.14.0a5-slim-bookworm" #python-preinstalled bookworm
        published_ports:
         - "9090:9090"
        pull: true
        restart_policy: "unless-stopped"
        state: started
        privileged: true
        interactive: true
        networks:
         - name: docker_net


