- name: Set up nginx hosts
  hosts: nginx
  gather_facts: false
  tasks:
    - name: Ensure nginx is installed
      ansible.builtin.package:
        name: nginx
        state: present
    - name: Ensure nginx service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: Ensure nginx exporters are installed
      ansible.builtin.package:
        name: prometheus-nginx-exporter
        state: present
    - name: /var/log/prometheus must exist for exporters to work
      ansible.builtin.file:
        path: "/var/log/prometheus/"
        state: directory
    - name: Make sure nginx proxy is using the pre-made config
      ansible.builtin.template:
        src: "configs/nginx/{{ inventory_hostname }}/default.j2"
        dest: /etc/nginx/sites-available/default
      register: configcopy
    - name: Reload nginx config
      ansible.builtin.command:
        cmd: nginx -s reload
      when: configcopy.changed
    - name: Start or check exporter service
      ansible.builtin.service:
        name: prometheus-nginx-exporter
        state: started
        enabled: true

- name: Set up nginx filehost
  gather_facts: false
  hosts: nginx-filehost
  tasks:
   - name: Serve bundled index.html
     ansible.builtin.copy:
       src: "content/nginx/{{ inventory_hostname }}/index.html"
       dest: /var/www/html/index.html
